FROM public.ecr.aws/lambda/nodejs:18

COPY app/package*.json ${LAMBDA_TASK_ROOT}/

RUN npm ci --production

COPY app/src/shared/ ${LAMBDA_TASK_ROOT}/src/shared/
COPY app/src/queries/ ${LAMBDA_TASK_ROOT}/src/queries/

CMD ["src/queries/index.handler"]